FROM node:16-alpine
WORKDIR /usr/src/stayyoung
COPY package.json ./
COPY package-lock.json ./
RUN npm install

ARG NEXT_PUBLIC_STAY_YOUNG_API
ENV NEXT_PUBLIC_STAY_YOUNG_API $NEXT_PUBLIC_STAY_YOUNG_API

ARG NEXT_PUBLIC_RECIPIENT_PHONE_NUMBER
ENV NEXT_PUBLIC_RECIPIENT_PHONE_NUMBER $NEXT_PUBLIC_RECIPIENT_PHONE_NUMBER

ARG NEXT_PUBLIC_DOMAIN_NAME
ENV NEXT_PUBLIC_DOMAIN_NAME $NEXT_PUBLIC_DOMAIN_NAME

COPY . .
RUN npm run build
CMD [ "npm", "start" ]