name: Stay Young UI Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_STAY_YOUNG_API=${{ vars.NEXT_PUBLIC_STAY_YOUNG_API }} \
            --build-arg NEXT_PUBLIC_RECIPIENT_PHONE_NUMBER=${{ vars.NEXT_PUBLIC_RECIPIENT_PHONE_NUMBER }} \
            --build-arg NEXT_PUBLIC_DOMAIN_NAME=${{ vars.NEXT_PUBLIC_DOMAIN_NAME }} \
            -t jagalive/stay-young-ui:${{ github.sha }} .
          docker tag jagalive/stay-young-ui:${{ github.sha }} jagalive/stay-young-ui:latest
        working-directory: ./

      - name: Push Docker image
        run: |
          docker push jagalive/stay-young-ui:${{ github.sha }}
          docker push jagalive/stay-young-ui:latest
